### ISSUE TITLE
parsing time out

### ISSUE THREAD

**Issue by nawak86** [SmartHomeIntegrationTech/MQTTServices-Daikin#2]
hello, 

Thanks for the development.
I managed to retrieve the information with MQTT. I use : https://github.com/domotruc/jMQTT
There is an option to convert in json the data but since he has too much info I have a browser time out.
how do you use the information retrieved via mqtt ?

Ty
++

**Comment by KarstenB** [comment]
Hmm, sorry, I don't think I can help you with that. If I understand you correctly, the data is arriving at MQTT broker as expected, right?

**Comment by nawak86** [comment]
hi

its ok now i have suscribe to : homie/daikin-heatingunit/spaceheating/# and homie/daikin-heatingunit/domestichotwatertank/#

thanks for update 0.0.2 i try this has soon as possible. i dont understand how to set a value after enabling.

I just want to set the boost mode for watertank if you can tell me more ;)

many thanks

**Comment by KarstenB** [comment]
I haven't tested it just yet for powerful, but I think you have to write a 1 to `homie/daikin-heatingunit/domestichotwatertank/2-operation-powerful/set` (and in your `PollingSettings.json` change settable to true for that node). Your exact topic may be different (i.e. a 0 or 1 instead of a 2 for powerful).

**Comment by KarstenB** [comment]
Let me know if you have any further issues. Closing this now.
